version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: ${PROJECT_NAME}_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MYSQL_USER: ${MYSQL_DATABASE_USER}
    volumes:
      - ${DATA_DIR}/mysql:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}_phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
    ports: 
      - ${PHPMYADMIN_PUBLIC_PORT}:80
  ojs:
    container_name: ${PROJECT_NAME}_ojs
    build: .
    ports:
      - ${OJS_PUBLIC_PORT}:80
    depends_on:
      - mysql
    volumes:
      - ${OJS_PUBLIC_DIR}:/var/www/html/public
      - ${OJS_FILES_DIR}:/var/www/files

    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: ${MYSQL_DATABASE_USER}
      DB_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE_NAME}
